spring:
  application:
  name: student-service

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  datasource:
    url: jdbc:mysql://bootify.co9ucvvetcr7.eu-west-2.rds.amazonaws.com:3306/bootify

spring:
  datasource:
  data-username: bootify
  datasource:
  data-password: bootify